[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nopm"
version = "0.0.1"
description = "Automate performance management reports from GitHub activity."
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "droctothorpe" }
]
license = { text = "MIT" }
dependencies = [
  "requests>=2.31.0",
  "pydantic",
  "pyyaml",
]

[project.optional-dependencies]
docx = [
  "python-docx>=1.1.0",
]
test = [
  "pytest",
]

dev = ["nopm[test,doc,docx]"]

[project.scripts]
nopm = "nopm.cli:main"

[tool.setuptools.packages.find]
include = ["nopm*"]
